name = "gacache"
version = "1.0.0"

description = "A simple actor based cache for erlang environments in gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "BradBot1", repo = "gleam_gacache" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_otp = ">= 0.10.0 and < 1.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
